
package org.example.echo.service.skeleton;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://service.enterprise.dansaranov.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @return
     *     returns org.example.echo.service.skeleton.ResultDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createProduct", targetNamespace = "http://service.enterprise.dansaranov.ru/", className = "org.example.echo.service.skeleton.CreateProduct")
    @ResponseWrapper(localName = "createProductResponse", targetNamespace = "http://service.enterprise.dansaranov.ru/", className = "org.example.echo.service.skeleton.CreateProductResponse")
    public ResultDTO createProduct();

    /**
     * 
     * @return
     *     returns org.example.echo.service.skeleton.ResultDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://service.enterprise.dansaranov.ru/", className = "org.example.echo.service.skeleton.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://service.enterprise.dansaranov.ru/", className = "org.example.echo.service.skeleton.PingResponse")
    public ResultDTO ping();

    /**
     * 
     * @param id
     * @return
     *     returns org.example.echo.service.skeleton.ResultDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeProductById", targetNamespace = "http://service.enterprise.dansaranov.ru/", className = "org.example.echo.service.skeleton.RemoveProductById")
    @ResponseWrapper(localName = "removeProductByIdResponse", targetNamespace = "http://service.enterprise.dansaranov.ru/", className = "org.example.echo.service.skeleton.RemoveProductByIdResponse")
    public ResultDTO removeProductById(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param categoryId
     * @return
     *     returns java.util.List<org.example.echo.service.skeleton.ProductDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductListByCategoryId", targetNamespace = "http://service.enterprise.dansaranov.ru/", className = "org.example.echo.service.skeleton.GetProductListByCategoryId")
    @ResponseWrapper(localName = "getProductListByCategoryIdResponse", targetNamespace = "http://service.enterprise.dansaranov.ru/", className = "org.example.echo.service.skeleton.GetProductListByCategoryIdResponse")
    public List<ProductDTO> getProductListByCategoryId(
        @WebParam(name = "categoryId", targetNamespace = "")
        String categoryId);

    /**
     * 
     * @return
     *     returns java.util.List<org.example.echo.service.skeleton.ProductDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://service.enterprise.dansaranov.ru/", className = "org.example.echo.service.skeleton.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://service.enterprise.dansaranov.ru/", className = "org.example.echo.service.skeleton.GetProductsResponse")
    public List<ProductDTO> getProducts();

    /**
     * 
     * @param id
     * @return
     *     returns org.example.echo.service.skeleton.ProductDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductById", targetNamespace = "http://service.enterprise.dansaranov.ru/", className = "org.example.echo.service.skeleton.GetProductById")
    @ResponseWrapper(localName = "getProductByIdResponse", targetNamespace = "http://service.enterprise.dansaranov.ru/", className = "org.example.echo.service.skeleton.GetProductByIdResponse")
    public ProductDTO getProductById(
        @WebParam(name = "id", targetNamespace = "")
        String id);

}
