
package org.example.echo.service.skeleton;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProductServiceService", targetNamespace = "http://service.enterprise.dansaranov.ru/", wsdlLocation = "http://localhost:8080/ProductService?wsdl")
public class ProductServiceService
    extends Service
{

    private final static URL PRODUCTSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.example.echo.service.skeleton.ProductServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.example.echo.service.skeleton.ProductServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ProductService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ProductService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PRODUCTSERVICESERVICE_WSDL_LOCATION = url;
    }

    public ProductServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductServiceService() {
        super(PRODUCTSERVICESERVICE_WSDL_LOCATION, new QName("http://service.enterprise.dansaranov.ru/", "ProductServiceService"));
    }

    /**
     * 
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServicePort")
    public ProductService getProductServicePort() {
        return super.getPort(new QName("http://service.enterprise.dansaranov.ru/", "ProductServicePort"), ProductService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServicePort")
    public ProductService getProductServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.enterprise.dansaranov.ru/", "ProductServicePort"), ProductService.class, features);
    }

}
